### ISSUE TITLE
Formatting breaks code, converting `else if` into `elseif` in some cases

### ISSUE THREAD

**Issue by daveschoutens** [nvuillam/npm-groovy-lint#127]
After running `npm-groovy-lint --format` on a project, I noticed it resulted in several compilation issues.

I tried to whittle the problematic code down to a minimal-ish example:
```groovy
    boolean foo(boolean a, boolean b) {
        if (a) {
            return true
        } else if(b) { // post-format, this breaks (ends up as `elseif`)
            return true
        }
    }
```
I found that if I add a space, like `else if (b) {` it stops exhibiting this behavior, but I'm not sure if that's the whole story.

**Comment by nvuillam** [comment]
That's nasty ^^
Reproduced, I'm on it ^^

**Comment by nvuillam** [comment]
I fixed the issue and released it in a beta version of next major release, please can you confirm it's ok with your whole file ? :)

`npm install -g npm-groovy-lint@8.0.0-beta.2`

**Comment by nvuillam** [comment]
Addendum: i had an beta release issue, so the beta to use is **npm-groovy-lint@8.0.0-beta.3** , not _npm-groovy-lint@8.0.0-beta.2_

**Comment by daveschoutens** [comment]
Looks like it's fixed :+1: 

Thanks!

**Comment by nvuillam** [comment]
Great :)
I'll close the issue when it will be delivered in main release and not beta ^^
Don't hesitate to notify if you see issues with the beta :) ( all test cases pass, but I still have some issues with VsCode Groovy Lint)
