### ISSUE TITLE
-v is documented as shorthand for "verbose", but is shorthand for "version"

### ISSUE THREAD

**Issue by ahwitz** [nvuillam/npm-groovy-lint#131]
`node_modules/.bin/npm-groovy-lint -f "*.gradle" -v`

Per the README, this should run verbosely, but instead I'm getting the following error:

> Parse options error: The options --files and --version are mutually exclusive - you cannot use them at the same time.

Running `--verbose` doesn't fail, but doesn't result in different output. I'm not able to get this library to run on any files with the above command, at the moment, but I don't know if that's my fault yet...

**Comment by nvuillam** [comment]
Hmmm indeed :)
Meanwhile, please can you use --verbose ?

**Comment by nvuillam** [comment]
Hmmm it seems indeed odd, i'll have a look :)

**Comment by nvuillam** [comment]
I fixed the doc (PR to come):
- `-v --version` for version
- `--verbose` for verbose

For the moment, --verbose only adds to the log the list of fixed errors.
If you really want more (huge?) logs, you can call : 
`DEBUG=npm-groovy-lint node_modules/.bin/npm-groovy-lint -f "*.gradle" --verbose`

Please can you try and tell me if it's ok for you ?
What are the kind of extra informations you need ?

**Comment by ahwitz** [comment]
The `--verbose` seems to work, but I haven't got to actually using it with `--fix` yet. Submitting another ticket in a sec with some inconsistencies with the `-f` flag that I ran into...
