### ISSUE TITLE
Consider excluding MethodReturnTypeRequired in recommended-jenkinsfile

### ISSUE THREAD

**Issue by felipecrs** [nvuillam/npm-groovy-lint#142]
I'm not sure about this one, but since we already exclude the `NoDef` rule, would not make sense to exclude this one as well?

In my example I have:

```groovy
def buildNpmProject() {} // return type is void (there is no return)
```

**Comment by nvuillam** [comment]
Agreed :) You can put that in the same PR than for FactoryMethodName :)
