### ISSUE TITLE
Disable rule in .groovylintrc.json for specific files

### ISSUE THREAD

**Issue by wheelerlaw** [nvuillam/npm-groovy-lint#154]
I want to disable the rules for `*.gradle` files. How do I do this in the `.groovylintrc` file?

**Comment by nvuillam** [comment]
You can't do that in .groovylintrc, but you can do that with arguments :)

Default **--files** values is `"**/*.groovy,**/Jenkinsfile,**/*.gradle"`

You can use `npm-groovy-lint --files "**/*.groovy,**/Jenkinsfile"` to ignore .gradle files
