### ISSUE TITLE
How to use the Docker image?

### ISSUE THREAD

**Issue by MaxGyver83** [nvuillam/npm-groovy-lint#156]
I tried using `npm-groovy-lint`'s official docker image, but I don't get any output at all. When I'm inside a directory containing many `.groovy` files and I run:

```sh
docker run -u "$(id -u):$(id -g)" -w=/tmp -v "$PWD":/tmp nvuillam/npm-groovy-lint
```

Then there is no output. Not even with:

```sh
docker run -u "$(id -u):$(id -g)" -w=/tmp -v "$PWD":/tmp nvuillam/npm-groovy-lint --version
```

Am I using it the wrong way?

**Comment by edmundadjei** [comment]
the files need to be either named Jenkinsfile or have a .groovy extension

**Comment by nvuillam** [comment]
@MaxGyver83 npm-groovy-lint needs to be called from the docker image
Is it better if you do the following ?

`docker run -u "$(id -u):$(id -g)" -w=/tmp -v "$PWD":/tmp nvuillam/npm-groovy-lint  --entrypoint "/bin/sh" npm-groovy-lint`

**Comment by MaxGyver83** [comment]
This gives me an error:

```shell
$ docker run -u "$(id -u):$(id -g)" -w=/tmp -v "$PWD":/tmp nvuillam/npm-groovy-lint --entrypoint "/bin/sh" npm-groovy-lint
Parse options error: Invalid option '--entrypoint' - perhaps you meant '--output'?
```

**Comment by okainov** [comment]
entrypoint needs to go before image name:

```bash
    docker run -u root -it --entrypoint /bin/bash -w=/tmp -v "$PWD":/tmp nvuillam/npm-groovy-lint
    # Now you're inside container, so you can run npm-groovy-lint in whatever way you need, like
    npm-groovy-lint -c .groovylintrc.json --no-insight --noserver -i '**/npm-groovy-lint/**' -o output.xml
```

**Comment by harishjangam6979** [comment]
@okainov - I tried the below after getting into the container. It run CodeNarc for ever.. 
```
$ docker run -it --entrypoint /bin/bash -v "$PWD:$PWD" docker.company.com/npm-groovy-lint
bash-5.0# npm-groovy-lint --no-insight
GroovyLint: Started CodeNarc Server
# Stays empty for long time and then shows the same below progress as Running CodeNarch for *m*s and runs for ever.. 
```

```
bash-5.0# npm-groovy-lint --no-insight --noserver
[████████████████████░░░░░░░░░░░░░░░░░░░░] Running CodeNarc for 2m6s
```

Any suggestions ?

**Comment by MaxGyver83** [comment]
> entrypoint needs to go before image name:

@okainov : Thank you. This works. Well, I had no `.groovylintrc.json`. So I ran it like this:

```bash
docker run -it -w=/tmp -v "$PWD":/tmp --entrypoint /bin/sh nvuillam/npm-groovy-lint
$ npm-groovy-lint --no-insight --noserver
```

Now it's easy running it in one step (non-interactively):

```bash
docker run -w=/tmp -v "$PWD":/tmp nvuillam/npm-groovy-lint npm-groovy-lint --no-insight --noserver
```

**Comment by nvuillam** [comment]
@MaxGyver83 don't hesitate to make a little PR if you want to enhance the doc :)

**Comment by MaxGyver83** [comment]
@nvuillam : I have tried again running the image using the command from the README and this time it works. I don't know what was wrong when I tried it the first time. Maybe I have updated the image in between. Or maybe I was just in a wrong directory when I ran the command back then.

**Comment by nvuillam** [comment]
I'm glad to hear your solved your issue :)
