### ISSUE TITLE
NglParseError not being disabled

### ISSUE THREAD

**Issue by htobonm7** [nvuillam/npm-groovy-lint#159]
Hi there!
I'm starting to use the `Groovy Lint, Format and Fix` VSCode extension but I'm having problems with the `NglParseError` rule. I have a Groovy class named `EnterHooks` and it seems to clash with one of the extension's classes which has the same name. Even though I disabled `NglParseError` for the entire project and for the file the error keeps popping up, highlighting the entire file, which is quite anoying. Look at my class and the error:

`class EnterHooks extends Base {}`

`Invalid duplicate class definition of class EnterHooks : The source /tmp/npm-groovy-lint/codeNarcTmpDir_0.2710115468781116/EnterHooks.groovy contains at least two definitions of the class EnterHooks.
One of the classes is an explicit generated class using the class statement, the other is a class generated from the script body based on the file name. Solutions are to change the file name or to change the class name.
 @ line 6, column 1.GroovyLint(NglParseError-0)`

I added `/* groovylint-disable NglParseError */` to the beginning of the file and to my `.groovylintrc.json` file as:

`"NglParseError": {
            "enabled": false
}`

Thanks for all the help.

**Comment by nvuillam** [comment]
NglParseError is unfortunately the only error you can't disable, because CodeNarc requires to be able to parse the file to be run :/

Please can you show your code ? The error seems explicit: You can't name a class in a file with the same name of the file

Let's say you have a file named **hello.groovy**, with the following content

```groovy
println "Hello World !"
```

During Groovy compilation (happening behind the scenes when you directly call a .groovy file), it generates something like

```groovy
public class hello {
    main(args) {
         println("Hello World")
     }
}
```

So if your hello.groovy contains :

```groovy
class hello {
         void someMethod() {
                println "Hello World !"
         }
}
```

at the compilation it tries to compile into : 

```groovy
public class hello {

    class hello {
             void someMethod() {
                    println "Hello World !"
             }
    }
}
```

See the hello class in double ? That's what generates the parsing error :)

**Comment by htobonm7** [comment]
> NglParseError is unfortunately the only error you can't disable, because CodeNarc requires to be able to parse the file to be run :/
> 
> Please can you show your code ? The error seems explicit: You can't name a class in a file with the same name of the file
> 
> Let's say you have a file named **hello.groovy**, with the following content
> 
> ```groovy
> println "Hello World !"
> ```
> 
> During Groovy compilation (happening behind the scenes when you directly call a .groovy file), it generates something like
> 
> ```groovy
> public class hello {
>     main(args) {
>          println("Hello World")
>      }
> }
> ```
> 
> So if your hello.groovy contains :
> 
> ```groovy
> class hello {
>          void someMethod() {
>                 println "Hello World !"
>          }
> }
> ```
> 
> at the compilation it tries to compile into :
> 
> ```groovy
> public class hello {
> 
>     class hello {
>              void someMethod() {
>                     println "Hello World !"
>              }
>     }
> }
> ```
> 
> See the hello class in double ? That's what generates the parsing error :)

Thank you @nvuillam for answering. I'm running this inside Jenkins and I have many files with classes that are named the same as the file without problems. I found the problem. At the end of the file I had a return statement outside the class, like this one:

`return new EnterHooks()`

I'm not sure why it's there. There are multiple people collaborating on this, I'll try to remove it. Anyway, thanks a lot for your help, I really appreciate it.

**Comment by nvuillam** [comment]
@htobonm7 you're welcome :)
You are right, if there is only the class in the file, it's ok, but if there is anything outside the class, it crashes ^^

Maybe it worked with groovy withing Jenkins, but it shouldn't work, so i advise you to remove all those `return new EnterHooks()`

Maybe try to see why it was put here before ^^
