### ISSUE TITLE
--fix ignored if -o is also provided

### ISSUE THREAD

**Issue by steven-terrana** [nvuillam/npm-groovy-lint#161]
Hello! 

Thank you for the work you put into this tool 🙌 .  

Starting testing it out today and integrating directly with existing codenarc rule sets and it's lovely. 

I noticed that when both `--fix` and `-o report.html` are provided, `npm-groovy-lint` does not automatically fix the issues it's able to. 

For example, creating a new directory and a single file **Example.groovy**

```groovy
class Example{
  void doThing(){ println "do thing" }
}
```

and then running: 
> npm-groovy-lint -p . --fix -o report.html --noserver

does not result in the automated fixes being applied.

I'm happy to look into this. If you have any tips that might point me in the right direction, i'd appreciate it :).

**Comment by nvuillam** [comment]
To be able to parse CodeNarc result, npm-groovy-lint requires CodeNarc Json output -> https://github.com/nvuillam/npm-groovy-lint/blob/8a21ad039435f72d1a2dab0d27e81553fc5bb790/lib/codenarc-caller.js#L347

Unfortunately, when using HTML or XML output, we don't have JSON output so we can just generate report, but not parse results, and --fix requires to result to be parseable -> 
https://github.com/nvuillam/npm-groovy-lint/blob/b234fcf6e0f8072c266a2afdfdbbedb39fbe9677/lib/codenarc-factory.js#L96

The solution would be to implement an evolution on CodeNarc to allow several report formats for a single lint
https://codenarc.org/codenarc-command-line.html
Something like `--report json:stdout --report myHtmlReportFile`
Then we could generate HTML output and apply auto-fix :)

**Comment by steven-terrana** [comment]
That makes a lot of sense. I'll look into this from the CodeNarc side. 

Thank you!
