### ISSUE TITLE
Module errors out when running with "use strict"

### ISSUE THREAD

**Issue by chinjon** [nvuillam/npm-groovy-lint#17]
Node version: 10.16.2
Npm version: 6.13.4

Issue:

Can't execute `npm-groovy-lint`, errors out with `use strict` within package.

![error-npm-groovy-lint](https://user-images.githubusercontent.com/12400487/78384198-bd0dae00-75a7-11ea-8ea4-ddf8ae788d6a.PNG)

**Comment by nvuillam** [comment]
I'm pretty sure it comes from node.js version, is it possible for you to upgrade to node 12 ?

**Comment by chinjon** [comment]
@nvuillam Thanks for responding so quickly! Wouldn't be possible due to requirements for the code base. I'll bring it up and see if its possible. 

Thanks so much for responding and maintaining the package. I'll close this issue.

**Comment by nvuillam** [comment]
I think i use some node 12 stuff, sorry !
Maybe it's possible to make several node versions live together ?
I keep node 10 compatibility in my backlog, and meanwhile i'll display an explicit error message if < node 12 :)
Thanks for your feedback !

**Comment by nvuillam** [comment]
I tried ... but is seems classs instance properties are supported only since NODE12, sorry  :/
![image](https://user-images.githubusercontent.com/17500430/78389847-c3ba1680-75e3-11ea-9753-8eeab118b1c8.png)

**Comment by nvuillam** [comment]
ps: for multiple nodes: https://medium.com/appseed-io/how-to-run-multiple-versions-of-node-js-with-nvm-for-windows-ffbe5c7a2b47 :)

**Comment by chinjon** [comment]
I didn't get any error messages when I installed golbally. I'll look into nvm. Thanks again for debugging/trying it out!
