### ISSUE TITLE
Separate executable and library files.

### ISSUE THREAD

**Issue by mariojaros** [nvuillam/npm-groovy-lint#174]
It would be nice to have separate executable files and library files because if code is running from another package it escalates problem with '#! /usr/bin/env node' which indicates that for example _groovy-lint.js_ is executable script and it wont compile with babel. It can be resolved with overriding webpack rules and by adding shebang loader, but if you have created react app then webpack can be override only with craco and it can be really annoying to set all rules right.

**Comment by nvuillam** [comment]
I don't have experience with babel, maybe u'd like to make a PR , or explain what you need with more details/ folder structure example ?

**Comment by nvuillam** [comment]
I agree that the shebang seems not nececssary in groovy-lint.js, please be my guest to make the PR :)

**Comment by mariojaros** [comment]
PR https://github.com/nvuillam/npm-groovy-lint/pull/175

**Comment by Morsina** [comment]
@mariojaros  hi bro, i may be have the same issue,  i cant use npm-groovy-lint in my react app (build by webpack 5), do you resolve this problem

**Comment by nvuillam** [comment]
The PR has been merged, is it still an issue ?

**Comment by daraghhiggins12** [comment]
> The PR has been merged, is it still an issue ?

I'm having issues building my application with webpack when using this module. Noted here https://github.com/nvuillam/npm-groovy-lint/issues/333

I don't think its related to this issue - just curious if anybody here has successfully integrated this while using webpack and react.

**Comment by nvuillam** [comment]
Are you trying to use npm-groovy-lint on the client side ? (to be used from browser)

If so, i'm afraid it won't work, as npm-groovy-lint runs external java executables
