### ISSUE TITLE
Support multiple report/output files

### ISSUE THREAD

**Issue by okainov** [nvuillam/npm-groovy-lint#176]
It would be great if npm-groovy-lint could parse multiple `-o` parameters and produce multiple reports.

Rationale: for example, for us we need both XML and JSON, XML is for Jenkins CodeNarc plugin to actually pass it to Jenkins and JSON for our own custom parsing and better reporting.

**Comment by okainov** [comment]
Well, I do think the issue should be still open.

**Comment by nvuillam** [comment]
That would be hard to do with the current architecture, especially knowing that CodeNarc (which is called behind) does not manage multiple output files, and npm-groovy-lint does not generate XML output, it just transfers back codeNarc generated one

Meanwhile CodeNarc decide to manage multiple output (if they do), I don't have any other workaround than calling twice npm-groovy-lint with different output formats :/
