### ISSUE TITLE
How to disable map files 

### ISSUE THREAD

**Issue by Yuceldd** [nvuillam/npm-groovy-lint#181]
Hello, firstly this is a great linter and I love using it, I have some files that includes just maps. I just want to linter dont check this files because I got NglBarseError because they are not a script. How to disable checking some files in a project ? I use that command 
` docker run -u "\$(id -u):\$(id -g)" -w=/tmp -v "\$PWD":/tmp nvuillam/npm-groovy-lint "**/globalSmartPipeline.groovy,**/GlobalSmartPipeline.groovy,**/*.gradle,**/*Jenkinsfile"`

The maps that I dont  want to be checked by linter is not included. 

Waiting for your help :)

**Comment by nvuillam** [comment]
What about renaming your files with an different extension, as they are not scripts ^^

for example `.groovymap` ?

**Comment by Yuceldd** [comment]
I wanted to check what I wrote the names of the files in the docker command and I realized that the docker command was a bit over scoped, I modified it (added   --files) and it works. This may be an easy issue but I am a very newbie to docker and other stuff  :) Thanks.  Great extension.
