### ISSUE TITLE
UnnecessaryGString incorrectly fixes regex

### ISSUE THREAD

**Issue by mwallace72** [nvuillam/npm-groovy-lint#189]
npm-groovy-lint@9.0.0

```
str.replace("\"", "")
```

Results in 
```
The String '"' can be wrapped in single quotes instead of double quotes  UnnecessaryGString
The String '' can be wrapped in single quotes instead of double quotes  UnnecessaryGString
```

And `--fix` generates 

```
str.replace("\'', "")
```

Which is invalid regex and Groovy

**Comment by nvuillam** [comment]
That's true , good catch !
Would you like to make a PR to solve this issue ?

**Comment by mwallace72** [comment]
@nvuillam I'll see if it's something I can fix

**Comment by nvuillam** [comment]
The fix should take place here :)
https://github.com/nvuillam/npm-groovy-lint/blob/master/lib/rules/UnnecessaryGString.js

If you can add a test case checking the issue you found , that's great !
