### ISSUE TITLE
Running npm groovy lint as a pre-commit hook

### ISSUE THREAD

**Issue by pirpirik** [nvuillam/npm-groovy-lint#193]
I created ".pre-commit-config.yaml" file in my repository and made the configuration below to use npm groovy lint as a pre commit hook.

repos: 
  - repo: https://github.com/nvuillam/npm-groovy-lint.git
    rev: v9.0.0
    hooks:
      - id: npm-groovy-lint
        name: Lint groovy files
        description: Groovy & Jenkinsfile Linter
        entry: npm-groovy-lint --output txt
        language: node
        types: [groovy]

And when I run pre-commit run command, at first linter automatically fixes the syntax according to the rules but after that turns it back on and gives this output.
PS C:\Users\abc\Desktop\PROJECTS\project> pre-commit run 
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to C:\Users\abc\.cache\pre-commit\patch1638728020-16208.
Lint groovy files....................................(no files to check)Skipped
[INFO] Restored changes from C:\Users\abc\.cache\pre-commit\patch1638728020-16208.

Is my configuration wrong or am I missing something? Can you please help? thanks in advance.

**Comment by nvuillam** [comment]
I think you just need node.js installed on your computer :)

@kevin-dimichel-dr any suggestion ? :) maybe to declare node.js as a dependency ?

**Comment by pirpirik** [comment]
Thank you for your quick response. I installed node.js and I push a commit to test it last night and it is still running :)) Is it normal, I'm not sure how long should I wait more.

**Comment by kevin-dimichel** [comment]
I recently got npm-groovy-lint working as a pre-commit hook after installing the pinned versions of java (zulu-8.70.0.23) and nodejs (20.3.1) using asdf.

Here's an example of the running it on the command line:

```shell
[terraform]$ pre-commit run format-npm-groovy-lint --all-files
npm-groovy-lint --format.................................................Failed
- hook id: format-npm-groovy-lint
- exit code: 1
- files were modified by this hook

/Users/kevin/projects/terraform/JenkinsPipeline.groovy


npm-groovy-lint results in  linted files:
┌─────────┬───────────┬─────────────┬─────────────┬─────────────────┐
│ (index) │ Severity  │ Total found │ Total fixed │ Total remaining │
├─────────┼───────────┼─────────────┼─────────────┼─────────────────┤
│    0    │  'Error'  │      0      │      0      │        0        │
│    1    │ 'Warning' │      0      │      0      │        0        │
│    2    │  'Info'   │     13      │     13      │        0        │
└─────────┴───────────┴─────────────┴─────────────┴─────────────────┘
Failure: 0 error(s) have been found
 0 warning(s) have been found
 13 info(s) have been found

```
