### ISSUE TITLE
More vulnerabilities in log4j 2.16

### ISSUE THREAD

**Issue by ppettina** [nvuillam/npm-groovy-lint#196]
According to https://logging.apache.org/log4j/2.x/security.html, a vulnerability could cause DOS with some crafted lookups.
This is fixed in log4j 2.17.

I'd be happy to post a patch when I find some time if no one else is able to, thought it might take a while to understand how to build/make changes to this project.

**Comment by nvuillam** [comment]
haha this CVE will never end ^^
I'll do that in the next days :)
But if you want to do it before, it's simple, just replace the JARs by the new ones, and make a big search/replace in the code ;)

Example in the previous PR: https://github.com/nvuillam/npm-groovy-lint/pull/195/files

**Comment by nvuillam** [comment]
Solved with @ppettina 's PR :)
