### ISSUE TITLE
Missing docker images for recent versions

### ISSUE THREAD

**Issue by ppettina** [nvuillam/npm-groovy-lint#197]
https://hub.docker.com/r/nvuillam/npm-groovy-lint/tags shows that the latest version available is v8.1.0.
I believe only @nvuillam is able to fix this though...

**Comment by nvuillam** [comment]
it is probablby an expired CI token, i'll have a look

https://github.com/nvuillam/npm-groovy-lint/actions/workflows/docker.yml

**Comment by nvuillam** [comment]
All good with 9.1 / latest :) ( i didn't rebuild previous versions because with log4j vulnerability they are not supposed to be used)

https://hub.docker.com/r/nvuillam/npm-groovy-lint/tags?page=1&ordering=last_updated
