### ISSUE TITLE
xml output ignores groovylint-disable comments 

### ISSUE THREAD

**Issue by wuillaum** [nvuillam/npm-groovy-lint#207]
Depending on what output format you choose, you get different results. It looks like `xml` ignores `groovylint-disable` comments, this seems like a bug to me!
```
$ npm-groovy-lint --output output.txt --output output.xml -f **/Jenkinsfile
GroovyLint: Successfully processed CodeNarc: 
CodeNarc completed: (p1=0; p2=20; p3=32) 616ms

$ npm-groovy-lint --output output.txt  -f **/Jenkinsfile
┌─────────┬───────────┬─────────────┐
│ (index) │ Severity  │ Total found │
├─────────┼───────────┼─────────────┤
│    0    │  'Error'  │      0      │
│    1    │ 'Warning' │      0      │
│    2    │  'Info'   │      4      │
└─────────┴───────────┴─────────────┘
GroovyLint: Logged results in file /home/support/output.txt
```

**Comment by nvuillam** [comment]
@wuillaum it is... and it is not... :)

npm-groovy-lint is a wrapper for CodeNarc, and when calling with xml output, npm-groovy-lint directly returns the XML provided by CodeNarc.

But luckily for your, they implemented the equivalent of groovylint-disable in a later version, so if you really want to use XML format (why?), you can replace the groovylint-disable by codenarc-disable in your sources, so CodeNarc will directly ignore what it is supposed to ignore :)

**Comment by wuillaum** [comment]
Interesting, thank you for the information.

I'm using `xml` output for the [warnings-ng](https://plugins.jenkins.io/warnings-ng/) Jenkins plugin to ingest the results and provide feedback on PRs.

Looking at the [supported formats](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/SUPPORTED-FORMATS.md) of the warnings-ng plugin, I don't think there's anything here that could be ingested by npm-groovy-lint's other export formats.

**Comment by nvuillam** [comment]
I see that this plugin supports lots of different tools & formats, most of them do not return XML (ex: brakeman)  -> https://github.com/jenkinsci/warnings-ng-plugin/blob/master/SUPPORTED-FORMATS.md

I'm pretty sure that one of the existing parsers manage SARIF format (which is recently supported by npm-groovy-lint), so I think you could create a plugin using `npm-groovy-lint --output sarif`


Another way is to directly use [MegaLinter](https://megalinter.github.io/latest/) in Jenkins, it embeds npm-groovy-lint and is [easy to define in a Jenkinsfile](https://megalinter.github.io/latest/installation/#jenkins)

Last option is to make a PR to npm-groovy-lint, to parse result XML , remove stuff in comments, then rebuild XML, but as you will need to make a parser in warnings-ng plugin anyway , it's the longest solution

**Comment by nvuillam** [comment]
@wuillaum  For example, you can see here that Brakeman parser uses JSON to parse to warnings-ng format :)

https://github.com/jenkinsci/analysis-model/blob/master/src/main/java/edu/hm/hafner/analysis/parser/BrakemanParser.java

**Comment by nvuillam** [comment]
... and there is a SARIF adapter & Parser :)

I don't know Jenkins internal architecture, but I'm sure that if you ask the good people, they'll tell you how to easily call it to parse npm-groovy-lint results with SARIF :) (and it will be better than CodeNarc XML, because it also returns position in the code for most issues :) )

https://github.com/jenkinsci/analysis-model/blob/master/src/main/java/edu/hm/hafner/analysis/parser/violations/SarifAdapter.java

**Comment by wuillaum** [comment]
Thanks for the input... I am going to take the easiest route and simply change the disables to `codenarc-disable`. It's a bummer that warnings-ng doesn't accept SARIF, it seems like it's something that should be supported out of the box.

IMO this plugin should document that the `xml` output is not "properly" parsed by npm-groovy-lint, unlike all of the other outputs.
