### ISSUE TITLE
`npm-groovy-lint` command hangs forever

### ISSUE THREAD

**Issue by cr3** [nvuillam/npm-groovy-lint#212]
Hi folk! I'm using `npm-groovy-lint@9.4.1` and the command `npm-groovy-lint --ignorepattern '**/node_modules/**/*' --loglevel warning --failon warning --no-insight` hangs when running on macos with node v17.4.0. Some of the things I tried:
* Node from brew and nvm, both v17.4.0 of course, same problem;
* Node from brew and nvm, both v16.3.something this time, works fine;
* On Linux, v17.4.0, works fine.

Please let me know if you'd like me to try anything else. Thank you!

**Comment by hsuhw** [comment]
Might not be your case, but I faced a situation that Node is not being able to resolve `localhost` due to Mac's firewall setting.

You can try adding the arg `--serverhost 127.0.0.1` to see if you faced the same problem.

**Comment by nvuillam** [comment]
You can also try to use option `--noserver` , but it's slower if you call npm-groovy-lint a lot of times (java is launched at every lint request)
