### ISSUE TITLE
Does not work on M1 Macs

### ISSUE THREAD

**Issue by rubixibuc** [nvuillam/npm-groovy-lint#214]
Cross posting, the java-caller library is not compatible with M1 macs

https://github.com/nvuillam/node-java-caller/issues/18

**Comment by nvuillam** [comment]
What version of java is installed on your computer ?

What is the value of JAVA_HOME ?

**Comment by rubixibuc** [comment]
I have the wrong version but I had thought the node-java-caller package would attempt to install the correct one.

**Comment by nvuillam** [comment]
Indeed, node-java-caller should install the good version

node-java-caller relies on njre, which itself relies on https://adoptopenjdk.net/ API

It seems that openJDK does not support M1 MAC architecture https://adoptopenjdk.net/releases.html

Browsing the net I found a solution: https://sudarakayasindu.medium.com/installing-openjdk-on-m1-macbook-pro-4188ce3f9cf0 , maybe you can try to install the good java version and see if it works ?

**Comment by rubixibuc** [comment]
With the right java version already instaled it does work

**Comment by rubixibuc** [comment]
> Indeed, node-java-caller should install the good version
> 
> node-java-caller relies on njre, which itself relies on https://adoptopenjdk.net/ API
> 
> It seems that openJDK does not support M1 MAC architecture https://adoptopenjdk.net/releases.html
> 
> Browsing the net I found a solution: https://sudarakayasindu.medium.com/installing-openjdk-on-m1-macbook-pro-4188ce3f9cf0 , maybe you can try to install the good java version and see if it works ?

With the right java version already installed it does work

**Comment by nvuillam** [comment]
Glad the workaround worked :)
