### ISSUE TITLE
Is there support for more aggressively opinionated code formatting?

### ISSUE THREAD

**Issue by red8888** [nvuillam/npm-groovy-lint#219]
In python there is a code formatter called "black" that is super opinionated and leaves little open ended wrt whitespace and how data structures and method calls look. I'm wondering if more aggressive formatting can be enabled with a switch in npm-groovy-lint?

Here is an example, all of these code blocks are valid while they are wildly different:
```
steps {
    script {
        container('mycontainer') {
            mycommand --blah 123
            myvar = myCustomStep argOne: 45, argTwo: false,
                argThree: "slkdjflksdjf",
                argFour: "slkdjflksdjf",
                argFive: env.BRANCH_NAME ?: 'mainline'
        }
    }
}

steps {
    script {
        container('mycontainer') {
            mycommand --blah 123
            myvar = myCustomStep argOne: 45, argTwo: false,

                argThree: "slkdjflksdjf",

                argFour: "slkdjflksdjf",

                argFive: env.BRANCH_NAME ?: 'mainline'
        }
    }
}

steps {
    script {
        container('mycontainer') {
            mycommand --blah 123
            myvar =
            myCustomStep argOne: 45, argTwo: false,
            argThree: "slkdjflksdjf",
            argFour: "slkdjflksdjf",
            argFive: env.BRANCH_NAME ?: 'mainline'
        }
    }
}

steps {
    script {
        container('mycontainer') {
            mycommand --blah 123
            myvar =
                myCustomStep argOne: 45, argTwo: false,
                argThree: "slkdjflksdjf",
                argFour: "slkdjflksdjf",
                argFive: env.BRANCH_NAME ?: 'mainline'
        }
    }
}

```

Is there like a --format --strict switch or something?

**Comment by nvuillam** [comment]
I am a big fan of black that I use on my python projects like [MegaLinter](https://megalinter.github.io/latest/) ❤️ 

npm-groovy-lint is just a wrapper of CodeNarc and its fixes are based on rules that are returned by CodeNarc... so I'm afraid the effort to make it black-like would be too big for my current available time , even if such requirement seems to be [wanted by the community for a while](https://github.com/jhipster/prettier-java/issues/44#issuecomment-502745946) :/

Maybe prettier guys would be interested ?
