### ISSUE TITLE
Auto-Fixable rules are not fixed

### ISSUE THREAD

**Issue by iPanCerT** [nvuillam/npm-groovy-lint#222]
Jenkinsfile: https://gist.github.com/iPanCerT/8ef35270aa9469999e7fc8dca6a4a1ee

Running npm-groovy-lint like this: `npm-groovy-lint --noserver --fix`

Getting this in the output:

  _7     info     There is whitespace between method name and parenthesis in a method call.  SpaceAfterMethodCallName
  9     info     There is whitespace between method name and parenthesis in a method call.  SpaceAfterMethodCallName_

I see from the docs that `SpaceAfterMethodCallName` & `SpaceAfterMethodCallName` are auto-fixable..
Yet they're not fixed..
Can you explain why?
I'm new to lint, sorry for the newbie question

version:

_CodeNarc version 2.2.0
npm-groovy-lint version 9.5.0
Groovy version 3.0.9 (superlite)_

**Comment by nvuillam** [comment]
Some CodeNarc rules and the messages they provide are sometimes hard to fix, it's sometimes not an exact science :/

**Comment by nvuillam** [comment]
@iPanCerT I added a fixing rule, all should be ok now with latest npm-groovy-lint v10, please can you confirm ?
