### ISSUE TITLE
Basic formatting is not working

### ISSUE THREAD

**Issue by mosheavni** [nvuillam/npm-groovy-lint#227]
Hi,
I'm trying to format my Jenkinsfile but for some reason it doesn't format it at all
Here's an example:
![image](https://user-images.githubusercontent.com/17252601/183613780-0e254008-0997-438f-b24f-5e810a404e9b.png)

CodeNarc is running:

```bash
❯ ps -ef | grep java
  502 50535     1   0 12:15PM ??         0:20.09 /usr/bin/java -Xms256m -Xmx2048m -cp /usr/local/lib/node_modules/npm-groovy-lint/lib/java/CodeNarcServer.jar:/usr/local/lib/node_modules/npm-groovy-lint/lib/java/* com.nvuillam.CodeNarcServer --server
```

Jenkinsfile:

```groovy
#!/usr/bin/env groovy
pipeline {
agent any
stages {
stage('Build and Upload Artifacts') {
when { expression { true } }
steps {
script {
    echo "hello"
}
}
}
}
}
```

Versions:

```bash
❯ node --version
v18.7.0

❯ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

❯ npm list -g | grep groovy
├── npm-groovy-lint@9.5.0
```

What am I missing? Why there's no debug flag? Some more verbosity to what's happening?
Any help would be appreciated 🙏🏼

**Comment by nvuillam** [comment]
Please could you share your Jenkinsfile source so I can reproduce the bug ?

**Comment by mosheavni** [comment]
> @mosheavni Please could you share your Jenkinsfile source so I can reproduce the bug ?

Yes so sorry.

```groovy
#!/usr/bin/env groovy
pipeline {
agent any
stages {
stage('Build and Upload Artifacts') {
when { expression { true } }
steps {
script {
    echo "hello"
}
}
}
}
}
```

**Comment by nvuillam** [comment]
I think it works fine with latest version :)

Please can you confirm it's ok on your side too ?

![image](https://user-images.githubusercontent.com/17500430/184529291-2c16703d-c002-4c9f-89ce-a0ce4fefdf93.png)
![image](https://user-images.githubusercontent.com/17500430/184529299-d82a27bf-78e3-409b-b824-8e2d4130e143.png)
![image](https://user-images.githubusercontent.com/17500430/184529305-e1bf851b-1803-45e0-8943-a7b64570c5a5.png)

**Comment by mosheavni** [comment]
Thanks!
