### ISSUE TITLE
Wrong line numbers

### ISSUE THREAD

**Issue by Reissner** [nvuillam/npm-groovy-lint#228]
[Matlab0.groovy.txt](https://github.com/nvuillam/npm-groovy-lint/files/9300866/Matlab0.groovy.txt)

In this file, well without extension txt, 
many references are with wrong line numbers. 
It is so frequenty, that I ask myself whether I do something principially wrong. 
I use with vs code.

**Comment by nvuillam** [comment]
Problem will be solved in next version of VsCode Groovy Lint, that will soon come :)

**Comment by nvuillam** [comment]
@Reissner it should be solved with VsCode Groovy Lint v2.0.0

Please can you reopen if you still have the issue ?
