### ISSUE TITLE
Multiple output format

### ISSUE THREAD

**Issue by damianszczepanik** [nvuillam/npm-groovy-lint#239]
As a outcome from linter job I'd like to have two formats of the report available. One is a default one which I leave as it is on console. Second JSON format I would like to use to build own summary which I can publish.

Based on documentation I can specify only one format for single execution. Then having two I need to lint twice same code.

**Comment by nvuillam** [comment]
Current architecture of npm-groovy-lint is not compliant with multiple output formats

If you really need such behaviour, there are several possibilites:

- Make a pull request in npm-groovy-lint, to allow --output argument to accept a list of outputs. Most of updates would happen [here](https://github.com/nvuillam/npm-groovy-lint/blob/master/lib/output.js) but you should also make sure to handle all the impacts by searching on `output` and `outputType` in the whole lib folder

- Use sarif output then convert back to human format , using tools like [sarif-fmt](https://crates.io/crates/sarif-fmt). That's what we do in [MegaLinter](https://oxsecurity.github.io/megalinter/latest/)  when we use SARIF_REPORTER
