### ISSUE TITLE
How to ignore, or not replace, double quotes with single quotes 

### ISSUE THREAD

**Issue by a4z** [nvuillam/npm-groovy-lint#240]
Hi, 

I am using this extension via the VS Code plugin, 

I would like to auto fix all a file, and it does an excellent job, but it also replaces `"` with `'`.
And I would like to turn that off, since we have double quotes everywhere.

But I can't find how that could work. What do I need to put into the `.groovylintrc.json` ?

**Comment by nvuillam** [comment]
The rule is `UnnecessaryGString` , if you disable it in .groovylintrc.json, its fixes won't be applied :)

**Comment by nvuillam** [comment]
But it may be a good idea to keep it active :) 

https://codenarc.org/codenarc-rules-unnecessary.html#unnecessarygstring-rule

**Comment by a4z** [comment]
Thanks a lot, Mr. Vuillamy! 
You just learned me a lot about Groovy.

**Comment by nvuillam** [comment]
Thanks a lot :)
But I'm an amateur in groovy, the credit goes to @chrismair and the team maintaining CodeNarc ;)
