### ISSUE TITLE
SARIF Format no Line/Column 

### ISSUE THREAD

**Issue by ButterBetzi** [nvuillam/npm-groovy-lint#251]
Hi,
like the problem mentioned in #248: there are further rules that sometimes do not include a line or a column in the SARIF result file.
All examples are listed below:
```
                {
                    "level": "warning",
                    "message": {
                        "text": "The parameter named axivion_builds in method call of class None does not match [a-z][a-zA-Z0-9]*"
                    },
                    "ruleId": "ParameterName",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 4
                                }
                            }
                        }
                    ],
                    "ruleIndex": 237
                },
```
                {
                    "level": "note",
                    "message": {
                        "text": "The line exceeds 120 characters. The line is 127 characters."
                    },
                    "ruleId": "LineLength",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 5
                                }
                            }
                        }
                    ],
                    "ruleIndex": 199
                },
```
                {
                    "level": "note",
                    "message": {
                        "text": "isNumber() can probably be rewritten as number"
                    },
                    "ruleId": "UnnecessaryGetter",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 14
                                }
                            }
                        }
                    ],
                    "ruleIndex": 330
                },
```
                {
                    "level": "warning",
                    "message": {
                        "text": "Class SoftwareVersion missing Javadoc"
                    },
                    "ruleId": "ClassJavadoc",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 0
                                }
                            }
                        }
                    ],
                    "ruleIndex": 36
                },
```
                {
                    "level": "warning",
                    "message": {
                        "text": "The type ArrayList should be replaced with an interface or more general parent class"
                    },
                    "ruleId": "ImplementationAsType",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 16
                                }
                            }
                        }
                    ],
                    "ruleIndex": 151
                },
```
                {
                    "level": "note",
                    "message": {
                        "text": "def for method parameter type should not be used"
                    },
                    "ruleId": "NoDef",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 24
                                }
                            }
                        }
                    ],
                    "ruleIndex": 220
                },
```
                {
                    "level": "warning",
                    "message": {
                        "text": "Number of parameters in method None.call exceeds maximum allowed (5)."
                    },
                    "ruleId": "ParameterCount",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 15
                                }
                            }
                        }
                    ],
                    "ruleIndex": 236
                },
```
                {
                    "level": "note",
                    "message": {
                        "text": "The method parameter [shallow] in class None was reassigned. Use a temporary variable instead."
                    },
                    "ruleId": "ParameterReassignment",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 15
                                }
                            }
                        }
                    ],
                    "ruleIndex": 238
                },
```
                {
                    "level": "note",
                    "message": {
                        "text": "(env.getProperty(BUILD_TARGET)) ? env.getProperty(BUILD_TARGET) : env.BUILD in class steps.None can be simplified to env.getProperty(BUILD_TARGET) ?: env.BUILD"
                    },
                    "ruleId": "TernaryCouldBeElvis",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 1
                                }
                            }
                        }
                    ],
                    "ruleIndex": 296
                },
```
                {
                    "level": "note",
                    "message": {
                        "text": "The code could be more concise by using a with() or identity() block"
                    },
                    "ruleId": "UnnecessaryObjectReferences",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "foo\\bar.groovy",
                                    "index": 10
                                }
                            }
                        }
                    ],
                    "ruleIndex": 340
                },

**Comment by nvuillam** [comment]
@ButterBetzi even with latest npm-groovy-lint version 11.1.1 ?

There are lots of rules with no exact location, but now most of them should return at least a line (and npm-groovy-lint builds a SARIF region from this line)

**Comment by ButterBetzi** [comment]
yes, unfortunately even with the newest version. Updated it before.

**Comment by ButterBetzi** [comment]
And fyi: with the cli output all of these errors have lines. It is only in the SARIF output that the lines are missing and therefore can't be mapped to a file on the jenkins.

**Comment by nvuillam** [comment]
thanks for the feedback, i'll check when i find some time ^^
