### ISSUE TITLE
npm-groovy-lint doesn't work for Java-17 (Temurin)

### ISSUE THREAD

**Issue by urvindar** [nvuillam/npm-groovy-lint#257]
Hi, 
As per my project requirements, I need to use - OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1  and npm-groovy-lint to catch groovy errors. 
I used the latest npm-groovy-lint version, and as per the below ERROR, it doesn't support beyond Java- 14.

**Java jre or jdk between 8 and 14 is required 
Installing Java jre 14 in /Users/ukaur/.java-caller...
Unexpected error: Unsupported architecture
Error: Unsupported architecture**

IS THERE A WAY TO MAKE IT WORK FOR JAVA-17?

**Comment by nvuillam** [comment]
I'm currently makeing a PR but npm-groovy-lint does not work with Java 17, because it is shipped with Groovy 3 that does not work with Java 17...
Investigating...

**Comment by urvindar** [comment]
U guys decide

**Comment by urvindar** [comment]
Glad to hear it!
