### ISSUE TITLE
Unclear lint warnings

### ISSUE THREAD

**Issue by lowrider59** [nvuillam/npm-groovy-lint#263]
107   warning  Found reference to java.sql.Statement  JdbcStatementReference
  208   warning  Found reference to java.sql.ResultSet  JdbcResultSetReference
  319   warning  The use of java.io.File violates the Enterprise Java Bean specification  JavaIoPackageAccess

Unclear to me, exactly why these are warnings at all...?
Is the last one relevant if we are running spring-boot (not EJB)

Is there somewhere a list of documentation of each warning-type 
with more info available?

**Comment by nvuillam** [comment]
You can see the list of codenarc rules here ->https://codenarc.org/codenarc-rule-index.html

If you use VsCode Groovy lint, you can go to the rule documentation (or ignore it) in one click :)

https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint

**Comment by lowrider59** [comment]
Very good!
Thanks for you quick & excellent support! :)

**Comment by nvuillam** [comment]
You're welcome :)
If you like the repo you can add your github star to it :)

![image](https://user-images.githubusercontent.com/17500430/212640809-d0cc62e7-95d6-4a05-8d13-ace49bfac6e9.png)

**Comment by lowrider59** [comment]
Done, thanks! :)
