### ISSUE TITLE
IntelliJ support?

### ISSUE THREAD

**Issue by bencehornak-gls** [nvuillam/npm-groovy-lint#265]
Is there a way to use this formatter with IntelliJ (which is probably the no. 1 IDE for Groovy)?

I found a plugin the [CodeNarc plugin](https://plugins.jetbrains.com/plugin/5925-codenarc), but it does not take the `.groovylintrc.json` into consideration, so it makes the development inconvenient for projects, where vscode (with the [vscode-groovy-lint](https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint)) and IntelliJ are both used.

**Comment by nvuillam** [comment]
Indeed Intellij embeds CodeNarc, which works with [RuleSets](https://codenarc.org/codenarc-creating-ruleset.html)

npm-groovy-lint is a wrapper of CodeNarc aiming to simplify its use, and is available only via command line or VsCode Groovy Lint 

Under the hood, .groovylintrc.json is partially converted into RuleSet format to be understood by CodeNarc

If you, or someone you know, would like to make a plugin for Intellij, I'll be glad to provide support :)
