### ISSUE TITLE
Questions about using project behind an API

### ISSUE THREAD

**Issue by verdverm** [nvuillam/npm-groovy-lint#266]
I've been looking at: https://nvuillam.github.io/npm-groovy-lint/#use-as-module

and I'd like to put this behind a REST API, but only for formatting at this point.

- Is there a way to create the linter object once and run it against a source as requests come in?
- The code looks to spin up a `CodeNarcServer` on invocation, is this something I would want to run as well, setting the appropriate config values (https://github.com/nvuillam/npm-groovy-lint/blob/master/lib/options.js)
- Anything else to be aware of? 

If you are interested, the context is to make a new formatter tool / container here: https://github.com/hofstadter-io/hof/tree/_dev/formatters

**Comment by nvuillam** [comment]
That would be great to have an api exposing npm-groovy-lint :) ( plz just refer to the repo in the doc and ask for GitHub stars haha ^^ )

You can see examples of uses in VsCode Groovy Lint

Ex: https://github.com/nvuillam/vscode-groovy-lint/blob/9ffe56c0b3a7487745ed42b7b63bf145899e788b/server/src/linter.ts#L190

If you want your api to be able to run requests in parallel, I'd suggest to create a Linter object for each call
