### ISSUE TITLE
require parentheses around log messages

### ISSUE THREAD

**Issue by drernie** [nvuillam/npm-groovy-lint#267]
One PR reviewer pointed out I was inconsistent in my use of parenthesis around log messages.

Is there an option to check for that? I could not find it.

**Comment by nvuillam** [comment]
I neer heard about a CodeNarc rule about that :/
Or even any linter analyzing the content of log message strings :/

**Comment by drernie** [comment]
Not really about the *contents*.  The issue is that sometimes I have:

`log.debug "msg"`

and other times

`log.debug("msg", e)`

Not a huge issue, but I can see why it looks weird.

**Comment by drernie** [comment]
More generally, is there a Groovy idiom for when parenthesis are required on method invocation?

**Comment by nvuillam** [comment]
Oh sorry I didn't get without the example, i though it was about `log.debug("(parenthesis here !)")` :)

I'm not purist enough to care about such detail... when I worked with Groovy, I also used to add return before the variable at the end of the method, even if it's not necessary... but I found it more readable :)

**Comment by nvuillam** [comment]
All the rules behind npm-groovy-lint are here, maybe there is some but I'm not sure: https://codenarc.org/codenarc-rule-index.html

You can also ask on CodeNarc repo, maybe they'd be ok to create a new rule for their next version, and it would land in npm-groovy-lint later :)

**Comment by drernie** [comment]
Interesting. This is the closest:
https://codenarc.org/codenarc-rules-unnecessary.html#unnecessaryparenthesesformethodcallwithclosure-rule
```
UnnecessaryParenthesesForMethodCallWithClosure Rule

Since CodeNarc 0.14

If a method is called and the only parameter to that method is an inline closure then the parentheses of the method call can be omitted.

Example of violations:

    [1,2,3].each() { println it }
```
That sort of implies that parentheses ARE necessary in other cases, but I can't see any way to configure it.

**Comment by drernie** [comment]
Asked over there. Thanks!
