### ISSUE TITLE
Usage in git pre-commit

### ISSUE THREAD

**Issue by Scrubi** [nvuillam/npm-groovy-lint#270]
Can this linter be used in git pre-commit hook, I've tried running it from bash script but it always "hangs" and nothing happens.

my script:
#!/bin/bash

exit_status=0
for file in $(git diff --cached --name-only --diff-filter=ACM | grep -e '\.groovy$')
do
    
    npm-groovy-lint $file
    lint_status=$?
    if [ $lint_status -ne 0 ]
      then
          echo Lint failed, read report above and fix issues found.
          exit_status=1
    fi
    
done

exit $exit_status

**Comment by nvuillam** [comment]
I'm not a pre-commit user... @kevin-dimichel , as u added the pre-commit config in the repo, maybe you can help ? :)

**Comment by kevin-dimichel** [comment]
@Scrubi - yes!  See the description of https://github.com/nvuillam/npm-groovy-lint/pull/182 for an example configuration
