### ISSUE TITLE
Ability to suppress only exit-code

### ISSUE THREAD

**Issue by pbrisbin** [nvuillam/npm-groovy-lint#274]
:wave: Hi there- I run the [Restyled](https://restyled.io/) project, a tool for running auto-formatters automatically as part of the PR process, and I'm integrating `npm-groovy-lint` right now. I currently have to wrap your tool in a script that does `|| true` to prevent the non-zero exit code on differences from being considered an error. This is not ideal, as it makes it impossible to locate true failures (such as failing to parse or other unexpected exceptions).

Most tools have a `--no-exit-code` or `--no-fail` option to still exit 0 when there were fixes made. At first, I thought `--failon=none` was exactly this option, but I now believe it's misleadingly named. It doesn't only stop it from _failing_, it stops it from fixing and formatting too.

So question 1: am I missing any existing option to do what I describe (just suppress the non-zero exit when issues are found/fixed) and question 2: if not, can you add one?

**Comment by nvuillam** [comment]
hi @pbrisbin :)

Thanks for your interest in npm-groovy-lint :)

I have some issues about finding time for maintenance... would you like to make a PR with --no-exit-code ?

I'd gladly accept it !
