### ISSUE TITLE
npm-groovy-lint --version freezing

### ISSUE THREAD

**Issue by nvuillam** [nvuillam/npm-groovy-lint#276]
Cf https://github.com/oxsecurity/megalinter/issues/1768

**Comment by fnickels** [comment]
I have been having a similar issue.  I am attempting to run `npm-groovy-lint -v` in a container.  It works fine when I launch the container locally, but when run in our Jenkins environment it just freezes.  The same is true when running `npm-groovy-lint`.

I made some progress getting things to run by doing the following:

```
      java --class-path '/usr/local/lib/node_modules/npm-groovy-lint/lib/java/CodeNarcServer.jar:/usr/local/lib/node_modules/npm-groovy-lint/lib/java/*' \
            com.nvuillam.CodeNarcServer --server  &

      sleep 5

      npm-groovy-lint --noserver ./

      jobs
      kill %1
      sleep 5
      jobs
```

but I can not get `npm-groovy-lint -v` to work.   This is super strange as I normally do not see behavior differences based on the host running the container.  Any suggestions are welcome.
