### ISSUE TITLE
Unable to turn off "Duplicate Class" check

### ISSUE THREAD

**Issue by echristley** [nvuillam/npm-groovy-lint#279]
We are using Groovy for Jenkins pipelines to run our CI.  As part of that, we have a repo full of Jenkinsfiles that do a lot of routine work for us.  Maybe it is an anti-pattern to put them all in one repo, but we don't want to spread them out all over the place.
Recently started using this plugin, 'cause it is excellent.  The only issue I've found is no apparent way to turn off "Invalid duplicate class definition of class Jenkinsfile :. . . ."
Is there a way to turn it off that I'm missing?  Is it possible to add a way?

**Comment by nvuillam** [comment]
@echristley i think this is a groovy parsing issue, not a linting issue -> https://stackoverflow.com/questions/31511228/error-while-executing-groovy-script

**Comment by echristley** [comment]
Interesting.  I think you're right.
I found that if I renamed "Jenkinsfile.one" to "Jenkinsfileone", the issue goes away.
