### ISSUE TITLE
Indentation block-close has wrong indentation level

### ISSUE THREAD

**Issue by macetw** [nvuillam/npm-groovy-lint#280]
Frequently, function declarations are more than one line. When this happens, the indentation of the starting "{" is misinterpreted to be at the indentation of that character, rather than the indentation of the first line of the declaration. For example:

```
void doAThingWithManyParameters(int foo,
                                String bar) {
    println("Do the thing foobar. ${foo}, ${bar}")
}
```
   ... and the result of `--fix` on this file is the following:
```
void doAThingWithManyParameters(int foo,
                                String bar) {
    println("Do the thing foobar. ${foo}, ${bar}")
                                }
```

Naturally, there should be no space in front of the curly-brace to close the function, but here it's lining up with the indentation on the second line of the declaration. (at "String")

Is there some kind of workaround?

**Comment by macetw** [comment]
An easy fix to this is to collapse all those arguments on one line. But in many cases, when there are default parameters or types with long names, it cannot be done under 120 characters (which is another limit of the linter).

**Comment by macetw** [comment]
... or when making a function call with a closure, there could be lists or maps defined in the parameters, making it very difficult.

**Comment by macetw** [comment]
https://github.com/nvuillam/npm-groovy-lint/blob/cd70bbd397c3aea9a481552010f0b4192234a394/lib/rules/BracesForMethod.js#L89
Hm, `... not detected by CodeNarc.`

**Comment by nvuillam** [comment]
Maybe it is solved by a later version of CodeNarc, but I lack of time for npm-groovy-lint maintenance for now :(
