### ISSUE TITLE
Java 19 support

### ISSUE THREAD

**Issue by myroslavablis** [nvuillam/npm-groovy-lint#281]
Is there a reason for Java constrained up to version 14 only? We are on 19, it would be lovely to use groovy-lint but ideally without having to manage multiple versions.

**Comment by nvuillam** [comment]
hi @myroslavablis , it should be compliant, but I critically lack of time to make the appropriate upgrades :( 

Maybe you'd like to make a PR ? :)

**Comment by Andrew15-5** [comment]
If this is a trivial/not hard task, and you can provide hints on which files should be modified, then maybe I can resolve the issue. I personally don't code in Java, but I do want to use "almost the only one groovy formatter there is" without using SDKMAN to inject a path to the 17th version.

**Comment by nvuillam** [comment]
@Andrew15-5 npm-groovy-lint is now compliant with java 20 thanks to @stevenh :)

**Comment by Andrew15-5** [comment]
```
:!java --version
openjdk 19-panama 2022-09-20
OpenJDK Runtime Environment (build 19-panama+1-13)
OpenJDK 64-Bit Server VM (build 19-panama+1-13, mixed mode, sharing)
```

```
:!java --version
openjdk 20.0.2 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+9-78)
OpenJDK 64-Bit Server VM (build 20.0.2+9-78, mixed mode, sharing)
```

```
:!java --version
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)
```

```
:!npm-groovy-lint --format %
Java jre or jdk 17 is required
Installing Java jre 17 in /home/andrew/.java-caller...
```

I don't know what compliant supposed to mean, but `npm-groovy-lint` v12.0.1 still downloads Java 17 even when Java 19/20/21 is used.
