### ISSUE TITLE
Not working integration with Warnings Next Generation Jenkins plugin using Sarif report

### ISSUE THREAD

**Issue by navrkald** [nvuillam/npm-groovy-lint#282]
Dear [nvuillam](https://github.com/nvuillam),
I have tried to integrate Jenkins with your tool npm-groovy-lint using Jenkins plugin [Warnings Next Generation](https://plugins.jenkins.io/warnings-ng/) using Sarif report, however no issues was imported. I have checked [their testing sarif report](https://github.com/jenkinsci/warnings-ng-plugin/blob/db07bfe4addb69a649ffc1cfcc7ec72ad3314041/plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/sarif.json) with report generated by npm-groovy-lint and they have slight differences in structure.
I am not sure on which side the bug is, but it would be nice to solve it, so we can integrate npm-groovy-lint with Jenkins.
Best regards,
David Navrkal.

**Comment by nvuillam** [comment]
SARIF format is supposed to be valid with official SARIF validator -> https://sarifweb.azurewebsites.net/Validation

Please could you test your npm-groovy-lint SARIF output on it and confirm it's valid ?
