### ISSUE TITLE
Html report contains disabled issues in groovy files annotated by groovylint-disable or groovylint-disable-next-line

### ISSUE THREAD

**Issue by navrkald** [nvuillam/npm-groovy-lint#283]
Dear [nvuillam](https://github.com/nvuillam),
I have tried to generate HTML reports using your tool npm-groovy-lint, however found out that disabling npm-groovy-lint issues in groovy files doesn't work when generating html report. I have quickly checked the source code and can see there is no support implemented such feature for HTML report. It's kind of unexpected behaviour and I had to spend not trivial mount of time founding where is the problem. It would be very welcome, if this missing feature will be visibly documented or implemented, so others using npm-groovy-lint will not spend their time trying to debug where is the problem.
Best regards,
David Navrkal.

**Comment by nvuillam** [comment]
HTML reports are generated directly by CodeNarc, there is no post-processing by npm-groovy-lint, contrary to other reporters ^^
