### ISSUE TITLE
npm-groovy-lint doesn't connects to server CodeNarc instance using node > 16

### ISSUE THREAD

**Issue by navrkald** [nvuillam/npm-groovy-lint#285]
Dear [nvuillam](https://github.com/nvuillam),
When running npm-groovy-lint when using major version bigger than 16, it never connects to CodeNarc server and fallbacks to `no server` mode. Issue is npm-groovy-lint is using as host name by default htts://localhost, which is resolved on node 17 and bigger as IPv6 "::1", but Java server CodeNarc is always started on IPv4 127.0.0.1.
There is workaround for this issue to run npm-groovy-lint using parametr `--serverhost http://127.0.0.1`.
Best regards,
David Navrkal.

**Comment by nvuillam** [comment]
Many thanks for the tip @navrkald !
Maybe it will help solve my PR for upgrading Groovy & Java ^^
