### ISSUE TITLE
"--failon info" doesn't work if using "--out my.html"

### ISSUE THREAD

**Issue by ryeleo** [nvuillam/npm-groovy-lint#295]
When I add `--out my.html` to my command, the `--failon info` feature seems to stop working -- I am *always* seeing `0` returned, even when I expect it to be `1`:
```
$ docker run --rm -u "$(id -u):$(id -g)" -w=/tmp -v "$PWD":/tmp nvuillam/npm-groovy-lint --failon info --verbose src test --output my.html
> ...trimmed output...
$ $?
> 0
```

**Comment by nvuillam** [comment]
@ryeleo the html output is provided by CodeNarc and not parsed, so when using HTML output there are many npm-groovy-lint features that are disabled
