### ISSUE TITLE
Is there a way to ignore unknown rules?

### ISSUE THREAD

**Issue by efenderbosch-atg** [nvuillam/npm-groovy-lint#325]
We are using codenarc 3.3.0 which has added a few rules, including `junit.SpockMissingAssert`. When trying lint our project, this exception is thrown:

```
Exception in thread "main" java.lang.AssertionError: No such rule named [SpockMissingAssert]. . Expression: ruleClass. Values: ruleClass = null

        removed for brevity

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at com.nvuillam.CodeNarcServer.runCodeNarc(CodeNarcServer.groovy:113)
        at com.nvuillam.CodeNarcServer.main(CodeNarcServer.groovy:102)
```

Our `.groovylintrc.json` is simply:

```json
{
  "codenarcRulesets": "config/codenarc.groovy"
}
```
Is there a way to ignore unknown rules, or to upgrade the ruleset known to the linter?

edit:

Also, what's the difference between the `--format` and `--fix` flags?

**Comment by nvuillam** [comment]
--format will handle just formatting rules but not really change the code, whereas --fix can handle more complex fixes, like remove a duplicate import for example :)

About the rulesets, npm-groovy-lint code is in javascript so unable to parse a groovy file, so using a codenarc.groovy rule won't work

About unknown rules... npm-groovy-lint is currently in bad shape but is supposed to embed the latest codenarc version, that will happen in the future , mostly thanks to the great efforts of @stevenh (but you are also welcomed to help ^^ )

**Comment by efenderbosch-atg** [comment]
It seems like reading the groovy file is working just fine and the [documentation](https://nvuillam.github.io/npm-groovy-lint/#configuration) shows it as supported.

Thanks. I'll just close this for now. We simply commented out the `SpockMissingAssert` rule in `config/codenarc.groovy`.
