### ISSUE TITLE
Using npm-groovy-lint as a module giving webpack errors

### ISSUE THREAD

**Issue by daraghhiggins12** [nvuillam/npm-groovy-lint#333]
Using npm-groovy-lint as a module giving webpack errors

First issue was due to webpack attempting to bundle the jars, groovy files, and other incompatible files. 
To gain some short-term progress I used the ignore-loader in webpack to ignore these files.

Now I am getting errors insinuating missing packages:

Module not found: Error: Can't resolve 'fs'  

I have tried implementing multiple different rules including setting the fs package as empty but doing this causes issues in my application.

Is this library compatible with react desktop application built using webpack 5?

**Comment by stevenh** [comment]
Do you have some example code which reproduces this?
