### ISSUE TITLE
ignorepattern not working?

### ISSUE THREAD

**Issue by LRWeber** [nvuillam/npm-groovy-lint#34]
I'm trying to use the `--ignorepattern` option on the command line, but it doesn't seem to be working as expected. Specifically, I would like to ignore the usual `node_modules` directory.
```
npm-groovy-lint --files '**/*.groovy' --ignorepattern '**/node_modules/*'
```
I've tried several variations on the pattern with no luck. Is this a bug, or am I just missing the right format?

I'm currently running on Windows 10 with:
```
npm-groovy-lint version 4.5.4

Embeds:
- CodeNarc version 1.5
- Groovy version 3.0.3 (superlite)
```

**Comment by nvuillam** [comment]
Oops, my bad, I simply forgot to take in account this option 😊 
You can go with --ignorepattern **/node_modules/** using new version 4.5.3 😃

**Comment by LRWeber** [comment]
I tried it out, and it's working now! Thank you! 🌟

**Comment by cvakiitho** [comment]
Hi Sorry to reopen, but it seems to be not working on macos? : 

`npm-groovy-lint --files '**/*.groovy' --ignorepattern 'bin/**/*'`

And results contain:

`/Users/i337562/devel/fiori.pipeline/bin/target/test-classes/vars/blabla.groovy`

**Comment by nvuillam** [comment]
Did you try npm-groovy-lint --files '**/*.groovy' --ignorepattern
'/bin/**/*' ? :)

Please can you send the full log ?

Le jeu. 21 mai 2020 à 15:41, Tomáš Hartmann <notifications@github.com> a
écrit :

**Comment by cvakiitho** [comment]
I tried, still the same, full log you mean with some verbose settings?

**Comment by cvakiitho** [comment]
```
~/devel/test   codestyle  npm-groovy-lint --files '**/*.groovy' --ignorepattern '/bin/**/*' 
GroovyLint: Started CodeNarc Server after 1 attempts
/Users/.../devel/test/bin/target/test-classes/vars/....groovy
  1     info     Method "call" has a dynamic return type  MethodReturnTypeRequired

/Users/.../devel/test/bin/target/test-classes/vars/....groovy
  5     info     Method "call" has a dynamic return type  MethodReturnTypeRequired
  48    warning  The line exceeds 120 characters. The line is 176 characters.  LineLength              

/Users/.../devel/test/bin/target/test-classes/vars/....groovy
  1     info     Method "call" has a dynamic return type  MethodReturnTypeRequired
  6     warning  The variable [startServer] in class None is not used  UnusedVariable          
  7     warning  The variable [startNote] in class None is not used  UnusedVariable         
```

**Comment by nvuillam** [comment]
Please can you try the following command and post the full log ? (in private to nicolas.vuillamy@gmail.com if you don't want your log details to be posted publicly :) )  
DEBUG=npm-groovy-lint npm-groovy-lint --files '**/*.groovy' --ignorepattern '/bin/**/*' --verbose

**Comment by nvuillam** [comment]
I think it would work with `--ignorepattern '**/bin/**'`, please can you check ? 😃

**Comment by nvuillam** [comment]
as discussed by mail, problem solved with `--ignorepattern '**/bin/**'` , I close again the issue :)
