### ISSUE TITLE
In case of grouped imports linter returns error NglParseError: unable to find class 'TestGroup.CAN' 

### ISSUE THREAD

**Issue by ixytiris** [nvuillam/npm-groovy-lint#371]
I notice that when i have more than 5 imports of the same package that are being grouped to one import like:
import com.test.annotations.*
linter throws a error : NglParseError : unable to find class 'TestGroup.CAN' for annotation attribute constant
As a workaround i remove the group and import all the imports individually

**Comment by ixytiris** [comment]
I notice that when i have more than 5 imports of the same package that are being grouped to one import like:
`import com.test.annotations.*`
linter throws a error : NglParseError  : unable to find class 'TestGroup.CAN' for annotation attribute constant
As a workaround i remove the group and import all the imports individually

**Comment by nvuillam** [comment]
I see there is a **NoWildcardImports Rule** on CodeNarc -> https://codenarc.org/codenarc-rules-imports.html

But it should not make the parsing crash :/
