### ISSUE TITLE
CodeNarcServer unexpected error: Parse Error: Invalid status code

### ISSUE THREAD

**Issue by guilcy** [nvuillam/npm-groovy-lint#374]
Hello,

I encounter following error message when using npm-groovy-lint on a debian 12.
[err.log](https://github.com/user-attachments/files/15585295/err.log)

As I am not familiar at all with node technology, I am stuck.

Software versions involved:
root@486be283f05f:/home/jenkins# npm-groovy-lint --version
GroovyLint: Successfully processed CodeNarc:
CodeNarc version 3.3.0
npm-groovy-lint version 14.6.0

Embeds:
CodeNarc version 3.3.0
- Groovy version 3.0.9 (superlite)

root@486be283f05f:/home/jenkins# npm list -g
/usr/local/lib
├── corepack@0.28.1
├── n@9.2.3
├── npm-groovy-lint@14.6.0
└── npm@10.7.0

openjdk 17.0.11 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode)

On another docker image with debian 11, with openjdk autoinstalled by npm-groovy-lint, with all above same version installed, I do not have the error.

Can you help to figure out the problem ? 

Details of the debian 12 package installed:
[apt-list.log](https://github.com/user-attachments/files/15585320/apt-list.log)
 
Maybe that was not the right place to share this problem (I am even not sure it is a npm-groovy-lint bug), apologize in that case just tell me where I should ask for support.

**Comment by guilcy** [comment]
I forgot to mention that the execution continues and seems properly terminating with expected detection done.
The command line used to reproduce the issue is: 
npm-groovy-lint  -i '**/.git/**' -o test.html scripts/**/*.groovy
Following command line does not shows errors:
npm-groovy-lint  -i '**/.git/**'  scripts/**/*.groovy

It seems the error is triggered by the use of "-o test.html" or "-o test.xml" on the command line.
run with "-o test.txt" or "-o test.json"  does not cause the error message

**Comment by guilcy** [comment]
little up to avoid closure of the ticket

**Comment by nvuillam** [comment]
@guilcy XML and HTML are direct calls to CodeNarc formatter, it's much better to use txt , json or sarif, as npm-groovy-llint handles pre-processing and post-processing :)

**Comment by guilcy** [comment]
I give it a try on nodejs 22.5.0, unfortunatly got the exact same behavior. 
I am wondering how to report that behavior to codenarc maintainer. I don't know what/how codenarc is getting called by npm-groovy-llint, neither how to reproduce it with codenarc alone.

I will check if we can get rid of the html rendering. (xml is not an issue we can suppress it).

**Comment by nvuillam** [comment]
@guilcy I added a troubleshooting section that will allow you to see more logs :)

https://nvuillam.github.io/npm-groovy-lint/#troubleshooting

**Comment by guilcy** [comment]
> @guilcy I added a troubleshooting section that will allow you to see more logs :)
> 
> https://nvuillam.github.io/npm-groovy-lint/#troubleshooting
@nvuillam I will try that, not soon but asap.

**Comment by nvuillam** [comment]
@guilcy thanks a lot :)

**Comment by guilcy** [comment]
@nvuillam I give it a try, unfortunatly I am not sure there is much info to understand the problem.
Please find the log attached:
[run-npm-groovy-linter.log](https://github.com/user-attachments/files/17260647/run-npm-groovy-linter.log)
