### ISSUE TITLE
Unable to disable indentation formatting

### ISSUE THREAD

**Issue by logicbomb421** [nvuillam/npm-groovy-lint#378]
It seems indentation is a common issue among users of CodeNarc, which I am aware this tool uses under the hood.

Our team has elected to disable the indentation rules entirely sine they are currently producing some odd results. However, when setting `enabled: false` for this rule, indentation is still modified on a call using `--fix` or `--format`.

For example, consider the following `.groovylintrc.json` file:
```json
{
  "extends": "recommended",
  "rules": {
    "Indentation": {
      "enabled": false
    }
  }
}
```
and the following Groovy snippet:
```groovy
int example(int arg) {
  if (arg == 1
      || arg == 2
      || arg == 3) {
      print(arg)
  } else {
        print(-1)
  }
}
```

When running the linter with `npm-groovy-lint example.groovy --fix` (or `--format`), the closing brace under `else` is still reformatted even though indentation should be disabled:
```groovy
if (arg == 1
    || arg == 2
    || arg == 3) {
    print(arg)
} else {
      print(-1)
    }
```

I have tried `formatting.Indentation` in the config file, though that also does not change anything.

How can I disable indentation linting  and formatting using this tool?

Thank you!

---
```
GroovyLint: Successfully processed CodeNarc: 
CodeNarc version 3.3.0
npm-groovy-lint version 14.6.0

Embeds:
CodeNarc version 3.3.0
- Groovy version 3.0.9 (superlite)
```

**Comment by nvuillam** [comment]
@logicbomb421 please can you run `DEBUG=npm-groovy-lint npm-groovy-lint ...` and share the log ?
It will tell use which rule has played with Indentation (there are other rules that can impact it)
