### ISSUE TITLE
Adding custom jar files for Groovy parsing

### ISSUE THREAD

**Issue by jsmithgmail** [nvuillam/npm-groovy-lint#427]
Hello.

Im receiving "Unknown parsing error" when parsing the groovy script where there is a custom import class. The classes reside in custom jar files. I tried to add the jar files to the groovy/lib folder, but still does not recognize the class. 

unable to resolve class <classname>\n @ line 7, column 1.\r\n   import <classname> \r\n   ^\r\n"  NglParseError

Is there a way to add external jar files to parse the groovy code? The error can be eliminated by adding --no-parse parameter, but would like to explore options to parse the groovy code.

Thank you.

**Comment by nvuillam** [comment]
The CodeNarc server takes only the text of the method as input parameter, no jars :/
What we need to find is a way to parse the groovy without it looking for external libraries and being unhappy to not find them
