### ISSUE TITLE
-x / --fixrules option doesn't work / is unclear how it's supposed to work

### ISSUE THREAD

**Issue by unitysipu** [nvuillam/npm-groovy-lint#57]
The instructions for the -x option are as follows
`-x, --fixrules String      List of rule identifiers to fix (if not specified, all available fixes will be applied) - default: all`

However I haven't been able to successfully execute this command. I've tried specifying some of the rules that --fix option handles without issues, such as `UnnecessaryDefInMethodDeclaration`

Running 
`npm-groovy-lint -x UnnecessaryDefInMethodDeclaration`
results in:
`Parse options error: The option 'fixrules' did not have its dependencies met.`

The default also is "all", but without any params I get the same error, also if i provide `-x all`, i still get the same error.

I'd like to run fixes one rule at a time so I can make clean commits.

**Comment by nvuillam** [comment]
@unitysipu > --fixrules is an option to --fix argument

You can try : 

`npm-groovy-lint --fix --fixrules UnnecessaryDefInMethodDeclaration`

**Comment by nvuillam** [comment]
@unitysipu > --fixrules is an option to --fix argument

You can try : 

`npm-groovy-lint --fix --fixrules UnnecessaryDefInMethodDeclaration`

**Comment by nvuillam** [comment]
Published in v5.3.0 :)
