### ISSUE TITLE
--fix fixes indentation even if it's ignored in .groovylintrc.json

### ISSUE THREAD

**Issue by unitysipu** [nvuillam/npm-groovy-lint#58]
`--fix` command is cool because it autofixes most issues in the codebase, however it also alters whitespaces / indentation even when i have specifically ignored those in the .groovylintrc.json

**Comment by unitysipu** [comment]
false alarm

**Comment by nvuillam** [comment]
Are you sure ?
I didn't find the time to investigate yet ^^

**Comment by unitysipu** [comment]
I tested and it seemed to work, I see some other kinds of white space changes in the diff after running --fix, but i think this particular issue is ok

**Comment by nvuillam** [comment]
There are [lots of rules](https://github.com/nvuillam/npm-groovy-lint/blob/master/lib/.groovylintrc-all.json#L181) adding/removing whitespaces, you can disable or customize them :)

        "formatting.SpaceAfterCatch": {},
        "formatting.SpaceAfterClosingBrace": {},
        "formatting.SpaceAfterComma": {},
        "formatting.SpaceAfterFor": {},
        "formatting.SpaceAfterIf": {},
        "formatting.SpaceAfterOpeningBrace": {},
        "formatting.SpaceAfterSemicolon": {},
        "formatting.SpaceAfterSwitch": {},
        "formatting.SpaceAfterWhile": {},
        "formatting.SpaceAroundClosureArrow": {},
        "formatting.SpaceAroundMapEntryColon": {},
        "formatting.SpaceAroundOperator": {},
        "formatting.SpaceBeforeClosingBrace": {},
        "formatting.SpaceBeforeOpeningBrace": {},
        "formatting.TrailingWhitespace": {},
