### ISSUE TITLE
--failonany option?

### ISSUE THREAD

**Issue by unitysipu** [nvuillam/npm-groovy-lint#60]
I noticed there are `--failoninfo`  `--failonwarning` and `--failonerror` but they cannot be used together. 

`--failoninfo` also doesn't seem to include warnings or errors (it's not an error level selector, which would make sense to some extent). The help documentation also seems to have a copy-paste issue as error and info have the same help text.

 --failonerror               Fails if at least one error is found
 --failonwarning             Fails if at least one warning is found
 --failoninfo                Fails if at least one error is found

Is there a way to configure this to return 1 if the report is not 100% clean. It's not clear from the help how that can be accomplished.

Tested with
npm-groovy-lint version 5.1.1

Embeds:
- CodeNarc version 1.5
- Groovy version 3.0.3 (superlite)

**Comment by nvuillam** [comment]
This was indeed messy :)
About to replace by a **failon** option :)

**Comment by nvuillam** [comment]
Published in v5.3.0 :)
