### ISSUE TITLE
--fix for indentation adds CRLF line-endings to all files it touches

### ISSUE THREAD

**Issue by unitysipu** [nvuillam/npm-groovy-lint#63]
I'm working primarily on linux and i've noticed when running --fix for indentation every file has LF line-endings turned to CRLF. The tool shouldn't mess with the file formatting this way.

**Comment by davegallant** [comment]
I wrote this a wrapper/workaround. It encapsulates the dependencies in a Dockerfile and includes `dos2unix` with an example:
https://github.com/davegallant/docker-groovy-lint

**Comment by aristotll** [comment]
similar problem

**Comment by nvuillam** [comment]
If i join the lines with os.EOL, will it be ok for you ?

https://nodejs.org/api/os.html#os_os_eol

**Comment by aristotll** [comment]
> If i join the lines with os.EOL, will it be ok for you ?
> 
> https://nodejs.org/api/os.html#os_os_eol

I think it will be ok

**Comment by nvuillam** [comment]
@unitysipu @davegallant @aristotll : published in latest patch, please reopen if there is still an issue :)

Note: not propagated to VsCode Groovy Lint yet
