### ISSUE TITLE
How to install npm-groovy-lint

### ISSUE THREAD

**Issue by sushreeta96** [nvuillam/npm-groovy-lint#66]
If we have company proxy i am unable to execute npm install -g npm-groovy-lint due to proxy settings. I have tried to perform npm config set proxy to my proxy and also npm config set registry  http://registry.npmjs.org/. But none of them yeilded positive results

**Comment by nvuillam** [comment]
It seems to be npm troubleshooting, not npm-groovy-lint related

I assume you have the same issue with all npm packages ?

Did you try all the solutions of this page ?

https://stackoverflow.com/questions/7559648/is-there-a-way-to-make-npm-install-the-command-to-work-behind-proxy

Alternatively, can you also try the following command and post the log here ? 

`npm install npm-groovy-lint -g --verbose`

**Comment by nvuillam** [comment]
I close the issue as it is not related to npm-groovy-lint itself

But I can continue helping you in the comments here :)

**Comment by sushreeta96** [comment]
Thank you that would be great. I will try out the fixes u pointed earlier today and if it still doesn’t work I will mail you in this mail chain itself

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sushreeta96** [comment]
I tried all the mentioned steps and none of them seem to work
