### ISSUE TITLE
Method testing

### ISSUE THREAD

**Issue by sushreeta96** [nvuillam/npm-groovy-lint#73]
I have a requirement of linting defined methods in groovy. The methods are not called in the script being linted. 

And as i was testing for how an error is treated by the npm-grovy-lint i saw that it isnt catching the Empty if statement error if its in the method.

Could you tell me how to lint methods that are not called as well?

**Comment by nvuillam** [comment]
Please could you post a sample of your code so i can reproduce the problem?

**Comment by nvuillam** [comment]
While i can't reproduce the bug i can't solve it, please reopen the issue with investigation infos :)
