### ISSUE TITLE
choose which rule when having both Jenkinsfile and groovy

### ISSUE THREAD

**Issue by sinkcup** [nvuillam/npm-groovy-lint#79]
the docs say:
> extends: Name of a base configuration (recommended, recommended-jenkinsfile, all)

but my project has two files: `Jenkinsfile` and `build.gradle`, if I choose `recommended-jenkinsfile`, how can I lint the groovy file `build.gradle`?

**Comment by nvuillam** [comment]
The linter will apply all rules to all files catched by --files argument (Ant style expression) 

If you want to use different sets of rules depending of the file type, you can perform 2 calls 

```shell
npm-groovy-lint --files **/*.gradle // Will use recommended

npm-groovy-lint --files**/Jenkinsfile --config recommended-jenkinsfile // Will use recommended-jenkinsfile
```

There is not yet a recommended-gradle, if you want to propose one in a PR, be my guest :)
