### ISSUE TITLE
Using codenarc.xml to define rules

### ISSUE THREAD

**Issue by srowan** [nvuillam/npm-groovy-lint#82]
Is it possible to leverage my existing codenarc.xml file to define the rules being used?

Since it seems likely there are other solutions, my desire is to have both:
1) VS-code highlighting of lint errors
2) lint validation in my gradle+groovy project build

I'm currently using the `ru.vyarus.quality` plugin, but could definitely swap that out if there's something that can work with npm-groovy-lint and use the same rule configuration.

**Comment by nvuillam** [comment]
If you define a npm-groovy-lint config file ( .groovylintrc.js ) at the root folder of your repo folder, both npm-groovy-lint and VsCode Groovy Lint will use it ( npm-groovy-lint is behind VsCode Groovy Lint)

Once your .groovylintrc.js file is defined :  
- VsCode Groovy Lint will automatically detect it , so no additional config
- Add `npm-groovy-lint` command in your gradle build instructions ( requires `npm install npm-groovy-lint -g` before

**Comment by nvuillam** [comment]
( and maybe someday i'll create a script to convert codenarc ruleset file into .groovylintrc.js 😄 )

**Comment by srowan** [comment]
Thanks! I'll try that.

**Comment by nvuillam** [comment]
I'm not a gradle expert, but as far as i know, to use npm-groovy-lint you need to call it via command line: there is no gradle plugin using it ( but there is a codenarc one, who reads codenarc rulesets )

If you don't find an ok solution, i'll try to manage VsCode Groovy Lint to use ruleset format but, but directly calling codenarc with code built using VsCode GroovyLint may trigger issues : for example, npm-groovy-lint has an [extended way to ignore rules](https://github.com/nvuillam/npm-groovy-lint#disabling-rules-in-source) , that code CodeNarc does not understand 

My best advice would be to succeed to call npm-groovy-lint via Gradle, then you'll be ok :)

Please let me know how you solved your case :)
